//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankor.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAction
    {
        public int id { get; set; }
        public int actionCode { get; set; }
        public string checkCode { get; set; }
        public System.DateTime uptoDT { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
