//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankor.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.AccountActions = new HashSet<AccountAction>();
            this.DeviceRegHistories = new HashSet<DeviceRegHistory>();
        }
    
        public int id { get; set; }
        public string account_num { get; set; }
        public string name { get; set; }
        public Nullable<int> ConsumerID { get; set; }
        public Nullable<int> person_id { get; set; }
        public Nullable<int> address_id { get; set; }
        public string loginName { get; set; }
        public string hashCode { get; set; }
        public Nullable<System.DateTime> dtCreate { get; set; }
        public Nullable<System.DateTime> dtDisable { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Confirmed { get; set; }

        public bool AllowEmailNotifications { get; set; }

        public virtual Address Address { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountAction> AccountActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceRegHistory> DeviceRegHistories { get; set; }
    }
}
