//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankor.Model.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class ClientInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientInfo()
        {
        }

        public int Id { get; set; }
        public string ClientName { get; set; }
        public string ContactInfo { get; set; }
        public string SiteAddress { get; set; }
        public string Smtp { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string QuestionEmail { get; set; }
    }
}

