//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankor.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceSetting
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string name { get; set; }
        public Nullable<int> id_modification { get; set; }
        public string fullModification { get; set; }
        public int id_class { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public Nullable<System.DateTime> NextVerification { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_transf { get; set; }
        public Nullable<int> id_utransf { get; set; }
        public Nullable<int> id_upd { get; set; }
        public Nullable<int> id_pollgroup { get; set; }
        public Nullable<int> id_subdiv { get; set; }
        public Nullable<int> id_address { get; set; }
        public Nullable<System.DateTime> DeviceDT { get; set; }
        public Nullable<System.DateTime> SystemDT { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public byte Tarifs { get; set; }
        public Nullable<double> PowerLimit { get; set; }
    
        //public virtual Address Address { get; set; }
        public virtual Device Device { get; set; }
        public virtual DeviceModification DeviceModification { get; set; }
    }
}
