//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ankor.Model.DAL
{
    public class DeviceDriverSpode
    {
        public int deviceDriverID { get; set; }
        public int spodesID { get; set; }

        public virtual DeviceDriver DeviceDriver { get; set; }
        public virtual SPODE SPODE { get; set; }
    }
}
