//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankor.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            //this.DeviceRegHistories = new HashSet<DeviceRegHistory>();
            this.Events = new HashSet<Event>();
            this.Measures = new HashSet<Measure>();
        }
    
        public int id { get; set; }
        public int factoryID { get; set; }
        public Nullable<long> IMEI { get; set; }
        public System.DateTime setupDT { get; set; }
        public Nullable<int> timeZoneID { get; set; }
        public Nullable<byte> hardID { get; set; }
        public Nullable<short> softID { get; set; }
        public Nullable<byte> paramID { get; set; }
        public Nullable<bool> hasRelay { get; set; }
        public Nullable<System.DateTime> productionDT { get; set; }
        public Nullable<float> UNominal { get; set; }
        public Nullable<float> INominal { get; set; }
        public Nullable<byte> Code { get; set; }
        public Nullable<int> RadioInfo { get; set; }
        public string Address { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DeviceRegHistory> DeviceRegHistories { get; set; }
        public virtual DeviceSetting DeviceSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Measure> Measures { get; set; }
    }
}
