//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankor.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceDriver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceDriver()
        {
            this.DeviceDriverSpodes = new HashSet<DeviceDriverSpode>();
        }
    
        public int id { get; set; }
        public Nullable<int> modificationID { get; set; }
        public Nullable<int> driverID { get; set; }
        public Nullable<bool> isDefault { get; set; }
        public string name { get; set; }
        public string comment { get; set; }
        public Nullable<bool> isUSPD { get; set; }
        public Nullable<short> channelsMask { get; set; }
    
        public virtual DeviceModification DeviceModification { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceDriverSpode> DeviceDriverSpodes { get; set; }
    }
}
