//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankor.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public long id { get; set; }
        public int deviceID { get; set; }
        public Nullable<int> eventCode { get; set; }
        public Nullable<short> nativeCode { get; set; }
        public System.DateTime startDT { get; set; }
        public Nullable<System.DateTime> stopDT { get; set; }
        public byte[] value { get; set; }
        public string description { get; set; }
        public bool IsNotified { get; set; }

        public virtual Device Device { get; set; }
        public virtual SpodesEvent SpodesEvent { get; set; }
        public virtual EventType EventType { get; set; }
    }
}
