//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankor.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetSpodesInfo
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string parentDesc { get; set; }
        public double OrderID { get; set; }
        public string OBIS { get; set; }
        public string DescRU { get; set; }
        public string DescEN { get; set; }
        public string IIC_Atr { get; set; }
        public string MeterClasses { get; set; }
        public Nullable<int> OKEI_ID { get; set; }
        public string title { get; set; }
    }
}
