//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankor.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OKEI
    {
        public int id { get; set; }
        public string title { get; set; }
        public string designationRUS { get; set; }
        public string designation { get; set; }
        public string symbolDesignationRUS { get; set; }
        public string symbolDesignation { get; set; }
        public Nullable<int> measureBase { get; set; }
        public Nullable<double> scale { get; set; }
        public Nullable<int> unitType_id { get; set; }
        public Nullable<bool> isNational { get; set; }
        public Nullable<bool> excluded { get; set; }
    
        public virtual UnitType UnitType { get; set; }
    }
}
