//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankor.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpodesEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpodesEvent()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int id { get; set; }
        public Nullable<short> id_spodesEventType { get; set; }
        public Nullable<short> code { get; set; }
        public string decription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual SpodesEventType SpodesEventType { get; set; }
    }
}
