//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankor.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GetAccountDevices
    {
        public int id_account { get; set; }
        public int id_device { get; set; }
        public System.DateTime changeDT { get; set; }
        public Nullable<System.DateTime> registerDT { get; set; }
        public Nullable<System.DateTime> breakDT { get; set; }
        public Nullable<int> breakReason { get; set; }
        public int tarifTypeID { get; set; }
        public string comment { get; set; }
        public Nullable<bool> Disabled { get; set; }
    }
}
